- CHANGELOG.md
- Cargo.toml
Move some deps into `dev-dependencies`. Ref: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#development-dependencies
We don't need people to pull these libraries when they use our library.
> Move test-only deps into dev-dependencies

- .github/workflows/localstack.yml
- .gitignore
- CHANGELOG.md
- Cargo.toml
- README.md
- deny.toml
- examples/README.md
- examples/hello_lambda/main.rs
- examples/template/main.rs
- scripts/read_logs.sh
- scripts/run_example.sh
- src/lambda.rs
- src/lib.rs
This PR adds a wrapper around the `lambda_runtime` package to make it easier to write lambda functions which are triggered by event source mappings to an SQS queue.
There is a certain amount of boiler-plate which is often recreated when setting up a lambda function. In general the process of iterating over the message batch and handling errors, etc, is not a problem we want to solve each time we write a lambda.
This implementation is an MVP version of this feature. A couple of missing features that will be added in future iterations are:
* Batch item error handling, so that individual failures of a message don't cause the entire batch to fail.
* A "reduce" step, to collect return values across the messages and then apply a function to the collected results.
* (?) Access to the raw …
> Add lambda::run_message_handler function

- .gitignore
- Cargo.toml
- deny.toml
- docker-compose.yml
- scripts/init-localstack.sh
- src/localstack.rs
- src/s3.rs
- test-data/some-prefix/nested-prefix/nested.txt
- test-data/some-prefix/prefixed.txt
- test-data/test.txt
This PR adds a function 
```
pub fn list_objects(
client: &Client,
bucket: impl Into<String>,
prefix: Option<String>,
) -> impl Stream<Item = Result<model::Object, SdkError<ListObjectsV2Error>>> + Unpin {
```
which generates a `Stream` of objects at a location in s3. Internally the function uses the `list_objects_v2` with pagination.
When processing many small files in S3 it can be helpful treat the object listing as a stream to be processed. This can also be helpful when analysing the contents of a bucket without needing to actually open the files.
This PR also adds support for running out unit tests in the context of a pre-prepared localstack instance. This allows us to do things like run listings against a pre-prepared s3 bucket and ensure that it behaves as expected.
> Add s3::list_objects to stream an object listing from a bucket

- Cargo.toml
- src/athena.rs
- src/lib.rs
Add an `athena::get_client()` helper function.
This adds support for building Athena clients that can be used with Localstack.
> Add support for localstack enabled Athena client

- CHANGELOG.md
- src/s3/async_put_object.rs
- src/s3/mod.rs
This PR implements a struct `AsyncPutObject` which implements `futures::AsyncWrite` and writes to s3 using the `put_object` API.
This API makes it easier to integrate stream processing functions with a final output destination in S3.
> Add s3::AsyncPutObject for async put object writes

- CHANGELOG.md
- Cargo.toml
- RELEASE.md
Bumps the version and updates the changelog for the 0.2.0 release.
We're ready for release 🚀
This is step 1 of https://github.com/harrison-ai/cobalt-aws/blob/main/RELEASE.md
> Prepare release 0.2.0

- CHANGELOG.md
- src/s3/async_put_object.rs
Remove the explicit calls to `cx.waker().wake_by_ref()`, instead delegating wakes to the underlying future.
I was curious to see if I could remove the calls to `cx.waker().wake_by_ref()`, which IIUC will essentially cause us to busy-wait the executor by immediately waking up whenever we're put to sleep. This seems to work, as long as we're careful to always poll the underlying future before returning `Poll::Pending`.
@timleslie could you please try this out and see if it behaves correctly for you, or if you're able to reproduce any of the deadlocking behaviour you saw previously?
N/A
> fix: Avoid busy-waiting the waker in `AsyncPutObject`.

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/sqs.rs
Adds an `sqs::get_client()` function to create an SQS client with LocalStack support.
This lets us setup multiple lambdas which communicate via SQS queues in a LocalStack environment.
> Add sqs::get_client

- CHANGELOG.md
- scripts/init-localstack.sh
- src/s3/mod.rs
- src/sqs.rs
This PR adds a function to push a stream of messages to an SQS queue with concurrent calls to `send_message_batch()`.
This function allows a stream of messages to be pushed to SQS quickly and efficiently.
> Add sqs::send_messages_concurrently()

- src/lambda.rs
Currently the records in a message are processed sequentially, this change allows concurrent processing of records in a message by using a stream.
Many processing tasks are I/O bound and allowing multiple records to be processed concurrently would help keep the CPU fully utilised during the lambda billing period.
Passing the `body` to the Anyhow context within the stream proved tricky, a tracing span would be nice but I'm not clear how that would work across `async` boundaries.
> feat: Concurrent record handling

- CHANGELOG.md
- src/lambda.rs
Adds public documentation for the `RECORD_CONCURRENCY` env var, and updates the CHANGELOG with a reference to this new feature.
We want all our features to be fully documented, and to have a comprehensive changelog.
I also made a slight cosmetic change to the code to hopefully make it more readable.
> Update docs to include `RECORD_CONCURRENCY`.

- CHANGELOG.md
- Cargo.toml
- src/config.rs
- src/lib.rs
This PR adds a function `config::load_from_env()`,  which creates an `SdkConfig` with LocalStack support.
Since `aws-sdk-*` `0.10.0`, the `SdkConfig` object supports setting the `endpoint_resolver()`. See https://github.com/awslabs/smithy-rs/pull/1300
This means users no longer need to set this endpoint on every client object they create. Instead, they can set it once on the shared `SdkConfig` object. In particular, this means we no longer need to support a `get_client()` function for every service. In a subsequent PR we will deprecate these functions, and then remove them in a subsequent reelase.
We still need to improve our testing of this functionality and LocalStack testing in general. For now, I've run a local experiment against a lambda which uses `aws_cobalt` and verified that it …
> Add config::load_from_env()

- CHANGELOG.md
- src/athena.rs
- src/s3/async_put_object.rs
- src/s3/mod.rs
- src/sqs.rs
This PR deprecates the `get_client()` functions in favour of the new `config::load_from_env()` function, which provides LocalStack support for all clients without the need for per-service hlper functions.
Now that `load_from_env()` exists, these functions no longer need to exist. Deprecating rather than deleting will allow users of the library a smoother transition path.
> Deprecate the get_client() family of functions

- Cargo.toml
Rolls back the version of `tracing-subscriber`.
The version we depend on has been yanked.
https://crates.io/crates/tracing-subscriber/versions
> chore: Update tracing-subscriber for yanked packages

- CHANGELOG.md
- scripts/read_logs.sh
- scripts/run_example.sh
- src/lambda.rs
This PR adds a workaround for some unexpected behaviour in the combination of LocalStack and `clap` which can cause environment variable parsing to fail when running Image based lambdas in LocalStack.
When running Image based lambdas in LocalStack, I observed that a command line argument of `handler.handler` was being provided to the rust binary process. I need to further investigate how/why this is being passed in. I believe it to be a bug, but I haven't confirmed that.
This command line value was in turn parsed by `clap` as part of our environment parsing. The behaviour of `clap` was to assign this command line value to the first element of the `Env` struct, and then ignore any environment variable provided for that element. This caused the wrong value to be provided to the `Env` struct …
> fix: Avoid failure if a handler argument is provided to the lambda

- CHANGELOG.md
- Cargo.toml
Bumped version number and updated changelog.
It's shipping time!
> Prepare 0.6.0 release

- Makefile
- examples/README.md
- scripts/read_and_validate_logs.sh
Update test-examples to include validation tests
Fixes #98 
To avoid visually inspecting that the correct log output is generated.
These changes have been tested on a aarch64 docker; Committing it here separately to let CI test without the M1 changes
* See the [data engineering handbook](https://dataengineering.harrisonai.io/pages/source_control.html#anatomy-of-a-pull-request) for more info.
> chore: Update read_logs.sh to include validation for test

- Cargo.toml
- Makefile
- README.md
- RELEASE.md
- about.hbs
- about.toml
- deny.toml
- licenses/licenses.html
Adds `Unicode-DFS-2016` to the list of allowed licenses, and adds a link to a generated page containing all used licenses to the `README.md`. 
The latest version of `unicode-ident` uses the `Unicode-DFS-2016` licences. We want to make sure we're doing due diligence and being as transparent as possible to the licenses used by the project, and ensuring all downstream license text is easily accessible by users of our project.
> task: Update allowed licenses

- src/s3/mod.rs
So that users can successfully copy-paste the suggested fix.
> Correct crate name in deprecation notice.

- docker-compose.yml
- src/sqs.rs
test: The SQS client has a max limit of 10 messages to retrieve and delete after it's done.
chore: docker-compose does not wait for the Localstack container to start to run
To perform batch operation on test consume queue (more #150 )
> [chore/tests] SQS consume multiple messages

- CHANGELOG.md
- Cargo.toml
- licenses/licenses.html
Prepares for the `0.8.0` release according to `RELEASE.md`.
We would like to publish an update with the latest `aws-*` dependencies and support for `clap` v4.
> Prepare for 0.8.0 release

- CHANGELOG.md
- Cargo.toml
- src/s3/async_multipart_put_object.rs
Adds the ability to resume an existing multipart upload, also adding a helper to expose the `upload_id` from a multipart upload.
So we can have a long-lived multipart upload that we can share around!
> feat: multipart session resumption #FRA-922

- docker-compose.yml
[This PR](https://github.com/harrison-ai/cobalt-aws/pull/196) failed the checks due to the rust version being 1.63.1.1. [Rust has now been updated](https://github.com/harrison-ai/dataeng-tooling-rust/commit/177e97702875760735d3143a610c254db1b1fcb0) 
This change reflects the new rust.
> Updated rust to 1.67-1.0 and changed version from 3.7 to 3.8

- .github/workflows/test-examples.yml
- .github/workflows/tests.yml
Run GHA CI checks on merge groups
This is apparently a pre-requisite to enabling merge queues, documented [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions)
N/A
> Run GHA CI on merge groups

- CHANGELOG.md
Updated dependencies, and not using `Endpoint 2.0` in this version
To prepare for new `cobalt-aws` version
> Update change log to prepare for version 0.10.0

- Cargo.toml
- licenses/licenses.html
Update the release version in cargo.toml and re-run `make licenses-report`
Po made silly mistakes
Po decides to code too late at night and isn't careful enough
> Update cargo.toml and licenses report v0.10.0

- docker-compose.yml
The rust docker images have moved to GHCR, update the reference to its new location per https://github.com/harrison-ai/dataeng-tooling-rust#rust-build-and-development-tooling-for-harrisonai
> Update Rust docker image location.

- CHANGELOG.md
- src/lambda.rs
This PR adds a function `running_on_lambda()`, which examines the environment variables to determine whether or not the binary is being run on AWS Lambda.
As part of the development cycle, needing to build an image and push it to AWS in order to run the handler can be time consuming, adding unnecessary friction to the dev cycle. This function gives an escape hatch to allow code to be run locally.
Subsequent PRs will add support for actually executing the message handler locally. For now, this PR just allows us to determine the running environment.
> feat: running_on_lambda()

- CHANGELOG.md
- examples/hello_lambda/main.rs
- examples/template/main.rs
- src/lambda.rs
This PR adds a `LocalContext` trait and `run_local_handler()` function.
This functionality gives us a way to run a `message_handler` locally. Let gives us the flexibility to write tools that can be run either as a Lambda, or as a local CLI tool/
> feat: LocalContext and run_local_handler

- Cargo.toml
This PR is focused on optimizing build times locally and includes basic testing to validate the improvements. It also involves disabling default features on the `aws_lambda_event` crate and only enabling `sqs` events.
There are no other PRs that need to be merged before this one.
Within this PR, the following changes have been made:
1. Disabled default features on `aws_lambda_event`: By disabling the default features, we ensure that no unnecessary features are included during the build process. This can significantly reduce compilation times and binary size.
2. Enabled only `sqs` events: For our specific use case, we only require `sqs` events from the `aws_lambda_event` crate. By enabling only this feature, we further optimize the crate for our requirements.
3. Basic Testing: Rudimentary …
> chore: aws_lambda_events build time

- CHANGELOG.md
- src/lambda.rs
This PR updates `run_local_handler` to accept message handlers with a return type other than `()`.
This limitation was an oversight in the initial implementation that restricts the use of this runner.
> fix: Accept return types other than () in run_local_handler

- CHANGELOG.md
- Cargo.toml
- Makefile
- scripts/read_and_validate_logs.sh
- scripts/run_example.sh
* Upgrades from Docker Compose V1 to Docker Compose V2
* Updates dependencies excluding the AWS SDK to their latest version. The AWS SDK update has a lot of breaking changes.
* Fixes a bug with `make test-examples` where destroying the previous localstack container wasn't removing the named volumes. This resulted in subsequent re-runs to error, as the queue being created already existed.
* Changes dependency versions to `major.minor` instead of `major.minor.build`, as the package is a library and we should let downstream packages select their desired build versions.
To keep our dependencies up to date for security and performance, and to ensure our developer experience is kept up to date for testing.
> fix: Update compose to V2, deps excl AWS

- Cargo.toml
- Makefile
- docker-compose.yml
- rust-dev.dockerfile
- scripts/Dockerfile-awslocal
- scripts/read_and_validate_logs.sh
- scripts/run_example.sh
- src/lambda.rs
- src/localstack.rs
- src/s3/async_multipart_put_object.rs
- src/s3/async_put_object.rs
- src/s3/mod.rs
- src/s3/s3_object.rs
- src/sqs.rs
- src/types.rs
In this PR, we're updating various AWS SDK dependencies for the `cobalt-aws` project to align with the latest versions and introducing support for LocalStack 3.0.2. Please provide feedback following the conventional comments guidebook to streamline the review process.
No other PRs.
This PR includes the following key changes:
1. **Dependency Updates**: 
- `aws-sdk-athena`: Upgraded from `0.29` to `1.10.0`.
- `aws-config`: Updated to `1.1.2` with the `behavior-version-latest` feature.
- `aws-sdk-s3`: Upgraded from `0.29` to `1.12.0`.
- `aws-sdk-sqs`: Upgraded from `0.29` to `1.10.0`.
- `aws-types`: Upgraded from `0.56` to `1.1.2`.
- `aws-smithy-async`: Added `1.1.2`.
- `aws-smithy-runtime-api`: Added `1.1.2`.
- `aws-smithy-http`: Removed.
2. **New Internal Structs**: 
- …
> Upgrade AWS crates and localstack

- Cargo.toml
Upgrade the crate toml version.
In order to release 0.13.1 the cargo.toml must be updated.
None
* See the [data engineering handbook](https://dataengineering.harrisonai.io/pages/source_control.html#anatomy-of-a-pull-request) for more info.
> Update the cargo toml version to 0.13.1

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
This PR adds feature flags `"s3", "sqs", "athena", "lambda"` to the crate.
For use cases where we only want to interact with one particular service, we want to be able to only pull in those `aws-sdk-*` crates that are absolutely necessary. These feature flags give the user that ability, which will reduce build times and binary sizes.
> feat: Add feature flags to crate

- CHANGELOG.md
- Cargo.toml
- proptest-regressions/s3/multipartcopy.txt
- src/s3/mod.rs
- src/s3/multipartcopy.rs
What changes have been made within this PR?
This PR introduces a new `S3MultipartCopier` struct for handling multipart copy operations in S3. The changes include:
- Implementing the `S3MultipartCopier` struct to efficiently copy large files (greater than 5GB) using multipart copy.
- Providing custom error handling for multipart copy operations.
- Integration tests to verify the functionality of multipart copy.
Why are we submitting this PR?
Currently, S3 copy operations only work for files up to 5GB. Multipart copy is not only necessary for larger files but is also much faster for files under 5GB due to parallel copies. However, multipart copy will make more API requests, potentially increasing costs. This PR addresses the need for efficient, scalable, and reliable copying of large …
> feat: multipart copy

- CHANGELOG.md
- Cargo.toml
- licenses/licenses.html
What changes have been made within this PR?
- This PR creates the release 0.13.4 for Cobalt-AWS.
- The release includes the following changes as per the change log:
- Added feature flags `"s3", "sqs", "athena", "lambda"`. By default, all features are enabled, so no breaking change.
- Added MultipartCopy to allow copy of files larger than 5GB.
Why are we submitting this PR?
- To officially release version 0.13.4 of `cobalt-aws`.
- To make the new features and improvements available to users.
Are there any other PRs that need to be merged first?
- No dependencies on other PRs.
- No specific concerns at this time.
- This release introduces property testing to help ensure more robust code.
* See the [data engineering handbook](https://dataengineering.harrisonai.io/pages/source_control.html#ana …
> chore: release 0.13.4

- CHANGELOG.md
- Cargo.toml
- about.toml
- licenses/licenses.html
- src/s3/mod.rs
This PR changes the return type of `s3::get_object()` from `Result<impl AsyncBufRead + Debug, SdkError<GetObjectError>>` to `Result<S3AsyncBufReader, SdkError<GetObjectError>>` where `pub type S3AsyncBufReader = IntoAsyncRead<FuturesStreamCompatByteStream>`.
This PR also bumps the version number in preparation for an immediate release.
This change allow us to use the returned value in places where a concrete type is required.
> task: Return concrete type from `s3::get_object()`

- docker-compose.yml
This PR update `cargo` to use the latest `1.81` release.
This lets us take advantage of the latest updates to the `cargo` toolchain.
> task: Upgrade cargo version

- docker-compose.yml
This PR removes the `version` field from `docker-compose.yml`.
This field is obsolete, and generates warnings in CI.
> task: Remove obsolete version from docker-compose

- Cargo.toml
- src/lambda.rs
Adds S3Event as a RunnableEventType 
So that lambdas can be triggered on S3Events
> feat: add s3event to run lambda handler

- CHANGELOG.md
- Cargo.toml
- src/sqs.rs
This PR adds a new-type `SQSQueueName(String)`, which implements validation as part of its `FromStr` implementation. It also updates the `queue_name` argument to `send_messages_concurrently()` from `&str` to `&SQSQueueName`.
It also includes the implementation of `proptest::Arbitrary`, exported as `sqs::test_support` via the `test-utils` feature flag.
This is a useful abstraction when working with SQS queues to a) ensure the correct type is being used, and b) that invalid names are never used.
> feat: Add SQSQueueName new-type

- CHANGELOG.md
- Cargo.toml
- about.toml
- deny.toml
- licenses/licenses.html
- src/s3/async_multipart_put_object.rs
This PR replaces the unmaintained crate `derivative` with `derive_more`.
It also prepares the release `0.15.1` so we can land this change quickly.
`derivative` now has a rust-sec advisory against it, and we don't want our consumers to be impacted by that.
> task: Replace derivative with derive_more

- CHANGELOG.md
- Cargo.toml
- licenses/licenses.html
This PR prepares the release of version `0.15.2` as per `RELEASE.md`.
We want a new release with the latest `aws_lambda_events` dependency.
> chore: Prepare release 0.15.2
